package com.tfg_rm.androidapp_restaurantmanager.data.remote.dto

import kotlinx.serialization.Serializable

/**
 * Data Transfer Object (DTO) used to request an access token using a verification code.
 *
 * @property code Unique code or temporary identifier provided to the employee for the validation process.
 * @property password Security password required to authorize the token generation.
 */
@Serializable
data class EmployeeTokenRequest(
    val code: String,
    val password: String
)

/**
 * Data Transfer Object (DTO) containing the authentication token generated by the server.
 *
 * @property token Character string representing the access token used to perform authenticated requests.
 */
@Serializable
data class EmployeeTokenResponse(
    val token: String,
)
